module.exports = {
  LISTA_COMPLETA: [
    "Allosaurus", "Amargasaurus", "Andrewsarchus", "Ankylosaurus", "Araneo",
    "Argentavis", "Arthropluera", "Baryonyx", "Basilosaurus", "Beelzebufo",
    "Bloodstalker", "Bulbdog", "Carcharodontosaurus", "Carbonemys", "Carnotaurus",
    "Castoroides", "Chalicotherium", "Crystal Wyvern", "Daeodon", "Deinonychus",
    "Desmodus", "Dilophosaurus", "Dimorphodon", "Diplodocus", "Dire Bear",
    "Direwolf", "Doedicurus", "Dunkleosteus", "Enforcer", "Equus",
    "Fasolasuchus", "Featherlight", "Ferox", "Frog", "Gallimimus",
    "Gasbags", "Giganotosaurus", "Glowtail", "Griffin", "Ichthyosaurus",
    "Iguanodon", "Karkinos", "Kaprosuchus", "Kentrosaurus", "Lymantria",
    "Maewing", "Magmasaur", "Managarmr", "Mantis", "Megalania",
    "Megachelon", "Megatherium", "Megalodon", "Megalosaurus", "Mesopithecus",
    "Micro-Raptor", "Morellatops", "Moschops", "Mosasaurus", "Onyc",
    "Ovis", "Paraceratherium", "Parasaur", "Pelagornis", "Phiomia",
    "Phoenix", "Pleasiosaur", "Procoptodon", "Pteranodon", "Pulmonoscorpius",
    "Purlovia", "Quetzal", "Raptor", "Ravager", "Reaper King",
    "Rex", "Rhyniognatha", "Rock Drake", "Roll Rat", "Sabertooth",
    "Sarco", "Shadowmane", "Shinehorn", "Snow Owl", "Spino",
    "Stegosaurus", "Tapejara", "Terror Bird", "Therizinosaurus", "Thorny Dragon",
    "Thylacoleo", "Titanoboa", "Titanosaur", "Triceratops", "Troodon",
    "Tusoteuthis", "Velonasaur", "Vulture", "Woolly Rhino", "Wyvern",
    "Yutyrannus"
  ],

  IMAGENES: {
    "Allosaurus": "https://ark.wiki.gg/images/0/09/Allosaurus.png",
    "Amargasaurus": "https://ark.wiki.gg/images/c/ca/Amargasaurus.png",
    "Andrewsarchus": "https://ark.wiki.gg/images/9/90/Andrewsarchus.png",
    "Ankylosaurus": "https://ark.wiki.gg/images/3/3a/Ankylosaurus.png",
    "Araneo": "https://ark.wiki.gg/images/d/df/Araneo.png",
    "Argentavis": "https://ark.wiki.gg/images/6/65/Argentavis.png",
    "Arthropluera": "https://ark.wiki.gg/images/c/cb/Arthropluera.png",
    "Baryonyx": "https://ark.wiki.gg/images/4/4a/Baryonyx.png",
    "Basilosaurus": "https://ark.wiki.gg/images/3/3b/Basilosaurus.png",
    "Beelzebufo": "https://ark.wiki.gg/images/2/27/Beelzebufo.png",
    "Bloodstalker": "https://ark.wiki.gg/images/5/52/Bloodstalker.png",
    "Bulbdog": "https://ark.wiki.gg/images/6/64/Bulbdog.png",
    "Carcharodontosaurus": "https://ark.wiki.gg/images/3/30/Carcharodontosaurus.png",
    "Carbonemys": "https://ark.wiki.gg/images/4/40/Carbonemys.png",
    "Carnotaurus": "https://ark.wiki.gg/images/c/c5/Carnotaurus.png",
    "Castoroides": "https://ark.wiki.gg/images/e/dc/Castoroides.png",
    "Chalicotherium": "https://ark.wiki.gg/images/1/12/Chalicotherium.png",
    "Crystal Wyvern": "https://ark.wiki.gg/images/8/87/Tropical_Crystal_Wyvern.png",
    "Daeodon": "https://ark.wiki.gg/images/a/a3/Daeodon.png",
    "Deinonychus": "https://ark.wiki.gg/images/c/c3/Deinonychus.png",
    "Desmodus": "https://ark.wiki.gg/images/0/07/Desmodus.png",
    "Dilophosaurus": "https://ark.wiki.gg/images/9/96/Dilophosaurus.png",
    "Dimorphodon": "https://ark.wiki.gg/images/4/45/Dimorphodon.png",
    "Diplodocus": "https://ark.wiki.gg/images/a/ad/Diplodocus.png",
    "Dire Bear": "https://ark.wiki.gg/images/7/77/Dire_Bear.png",
    "Direwolf": "https://ark.wiki.gg/images/a/a0/Direwolf.png",
    "Doedicurus": "https://ark.wiki.gg/images/2/22/Doedicurus.png",
    "Dunkleosteus": "https://ark.wiki.gg/images/1/1d/Dunkleosteus.png",
    "Enforcer": "https://ark.wiki.gg/images/e/eb/Enforcer.png",
    "Equus": "https://ark.wiki.gg/images/0/0b/Equus.png",
    "Fasolasuchus": "https://ark.wiki.gg/images/a/ae/Fasolasuchus.png",
    "Featherlight": "https://ark.wiki.gg/images/1/14/Featherlight.png",
    "Ferox": "https://ark.wiki.gg/images/4/4c/Ferox_Large.png",
    "Frog": "https://ark.wiki.gg/images/2/27/Beelzebufo.png",
    "Gallimimus": "https://ark.wiki.gg/images/e/e0/Gallimimus.png",
    "Gasbags": "https://ark.wiki.gg/images/6/6c/Gasbags.png",
    "Giganotosaurus": "https://ark.wiki.gg/images/c/c3/Giganotosaurus.png",
    "Glowtail": "https://ark.wiki.gg/images/c/cd/Glowtail.png",
    "Griffin": "https://ark.wiki.gg/images/3/30/Griffin.png",
    "Ichthyosaurus": "https://ark.wiki.gg/images/6/6a/Ichthyosaurus.png",
    "Iguanodon": "https://ark.wiki.gg/images/a/ac/Iguanodon.png",
    "Karkinos": "https://ark.wiki.gg/images/5/5e/Karkinos.png",
    "Kaprosuchus": "https://ark.wiki.gg/images/b/b7/Kaprosuchus.png",
    "Kentrosaurus": "https://ark.wiki.gg/images/d/dd/Kentrosaurus.png",
    "Lymantria": "https://ark.wiki.gg/images/e/ea/Lymantria.png",
    "Maewing": "https://ark.wiki.gg/images/5/53/Maewing.png",
    "Magmasaur": "https://ark.wiki.gg/images/a/a8/Magmasaur.png",
    "Managarmr": "https://ark.wiki.gg/images/e/ec/Managarmr.png",
    "Mantis": "https://ark.wiki.gg/images/e/ef/Mantis.png",
    "Megalania": "https://ark.wiki.gg/images/5/56/Megalania.png",
    "Megachelon": "https://ark.wiki.gg/images/0/00/Megachelon.png",
    "Megatherium": "https://ark.wiki.gg/images/1/1a/Megatherium.png",
    "Megalodon": "https://ark.wiki.gg/images/1/1a/Megalodon.png",
    "Megalosaurus": "https://ark.wiki.gg/images/a/a0/Megalosaurus.png",
    "Mesopithecus": "https://ark.wiki.gg/images/2/28/Mesopithecus.png",
    "Micro-Raptor": "https://ark.wiki.gg/images/5/57/Microraptor.png",
    "Morellatops": "https://ark.wiki.gg/images/a/ae/Morellatops.png",
    "Moschops": "https://ark.wiki.gg/images/0/05/Moschops.png",
    "Mosasaurus": "https://ark.wiki.gg/images/a/a8/Mosasaurus.png",
    "Onyc": "https://ark.wiki.gg/images/f/f6/Onyc.png",
    "Ovis": "https://ark.wiki.gg/images/0/07/Ovis.png",
    "Paraceratherium": "https://ark.wiki.gg/images/7/74/Paraceratherium.png",
    "Parasaur": "https://ark.wiki.gg/images/7/76/Parasaur.png",
    "Pelagornis": "https://ark.wiki.gg/images/f/fa/Pelagornis.png",
    "Phiomia": "https://ark.wiki.gg/images/0/04/Phiomia.png",
    "Phoenix": "https://ark.wiki.gg/images/1/12/Phoenix.png",
    "Pleasiosaur": "https://ark.wiki.gg/images/1/11/Plesiosaur.png",
    "Procoptodon": "https://ark.wiki.gg/images/5/51/Procoptodon.png",
    "Pteranodon": "https://ark.wiki.gg/images/c/c7/Pteranodon.png",
    "Pulmonoscorpius": "https://ark.wiki.gg/images/9/91/Pulmonoscorpius.png",
    "Purlovia": "https://ark.wiki.gg/images/4/42/Purlovia.png",
    "Quetzal": "https://ark.wiki.gg/images/4/4a/Quetzal.png",
    "Raptor": "https://ark.wiki.gg/images/0/07/Raptor.png",
    "Ravager": "https://ark.wiki.gg/images/d/df/Ravager.png",
    "Reaper King": "https://ark.wiki.gg/images/4/4c/Reaper_King.png",
    "Rex": "https://ark.wiki.gg/images/0/04/Rex.png",
    "Rhyniognatha": "https://ark.wiki.gg/images/5/52/Rhyniognatha.png",
    "Rock Drake": "https://ark.wiki.gg/images/d/dd/Rock_Drake.png",
    "Roll Rat": "https://ark.wiki.gg/images/b/ba/Roll_Rat.png",
    "Sabertooth": "https://ark.wiki.gg/images/0/03/Sabertooth.png",
    "Sarco": "https://ark.wiki.gg/images/6/64/Sarco.png",
    "Shadowmane": "https://ark.wiki.gg/images/0/01/Shadowmane.png",
    "Shinehorn": "https://ark.wiki.gg/images/2/20/Shinehorn.png",
    "Snow Owl": "https://ark.wiki.gg/images/d/df/Snow_Owl.png",
    "Spino": "https://ark.wiki.gg/images/0/08/Spino.png",
    "Stegosaurus": "https://ark.wiki.gg/images/c/cc/Stegosaurus.png",
    "Tapejara": "https://ark.wiki.gg/images/4/41/Tapejara.png",
    "Terror Bird": "https://ark.wiki.gg/images/a/a4/Terror_Bird.png",
    "Therizinosaurus": "https://ark.wiki.gg/images/2/23/Therizinosaurus.png",
    "Thorny Dragon": "https://ark.wiki.gg/images/1/1d/Thorny_Dragon.png",
    "Thylacoleo": "https://ark.wiki.gg/images/4/4e/Thylacoleo.png",
    "Titanoboa": "https://ark.wiki.gg/images/c/cd/Titanoboa.png",
    "Titanosaur": "https://ark.wiki.gg/images/d/dc/Titanosaur.png",
    "Triceratops": "https://ark.wiki.gg/images/6/62/Triceratops.png",
    "Troodon": "https://ark.wiki.gg/images/a/a7/Troodon.png",
    "Tusoteuthis": "https://ark.wiki.gg/images/b/b7/Tusoteuthis.png",
    "Velonasaur": "https://ark.wiki.gg/images/3/35/Velonasaur.png",
    "Vulture": "https://ark.wiki.gg/images/a/a2/Vulture.png",
    "Woolly Rhino": "https://ark.wiki.gg/images/2/23/Woolly_Rhino.png",
    "Wyvern": "https://ark.wiki.gg/images/4/46/Lightning_Wyvern.png",
    "Yutyrannus": "https://ark.wiki.gg/images/c/c9/Yutyrannus.png"
  }
};
