module.exports = {
  LISTA_COMPLETA: [
    // A
    "Achatina", "Acrocanthosaurus", "Allosaurus", "Ammonite", "Angler",
    "Ankylosaurus", "Araneo", "Archaeopteryx", "Archelon", "Argentavis",
    "Armadoggo", "Arthropluera", "Astrocetus", "Astrodelphis",
    // B
    "Baryonyx", "Basilisk", "Basilosaurus", "Beelzebufo", "Bison",
    "Bloodstalker", "Brontosaurus", "Bulbdog", "Burrowbuck",
    // C
    "Carbonemys", "Carcharodontosaurus", "Carnotaurus", "Castoroides",
    "Cat", "Ceratosaurus", "Chalicotherium", "Cnidaria", "Coelacanth",
    "Compy", "Cosmo", "Cryolophosaurus",
    // D
    "Daeodon", "Deathworm", "Deinonychus", "Deinosuchus", "Deinotherium",
    "Desmodus", "Dilophosaur", "Dimetrodon", "Dimorphodon", "Diplocaulus",
    "Diplodocus", "Dire Bear", "Direwolf", "Dodo", "Doedicurus",
    "Drakeling", "Dreadnoughtus", "Dung Beetle", "Dunkleosteus",
    // E
    "Electrophorus", "Enforcer", "Enigmasaur", "Equus", "Eurypterid",
    // F
    "Fasolasuchus", "Featherlight", "Ferox",
    // G
    "Gacha", "Gallimimus", "Gasbags", "Giant Bee", "Gigadesmodus",
    "Giganotosaurus", "Gigantopithecus", "Gigantoraptor", "Gloon",
    "Glowbug", "Glowtail", "Griffin",
    // H
    "Helicoprion", "Hesperornis", "Hyaenodon",
    // I
    "Ichthyornis", "Ichthyosaurus", "Iguanodon",
    // J
    "Jerboa", "Jug Bug",
    // K
    "Kairuku", "Kaprosuchus", "Karkinos", "Kentrosaurus",
    // L
    "Lamprey", "Leech", "Leedsichthys", "Liopleurodon", "Lymantria",
    "Lystrosaurus",
    // M
    "Maewing", "Maeguana", "Magmasaur", "Mammoth", "Managarmr", "Manta",
    "Mantis", "Megalania", "Megaloceros", "Megalodon", "Megalosaurus",
    "Meganeura", "Megatherium", "Megaraptor", "Mesopithecus", "Microraptor",
    "Morellatops", "Mosasaurus", "Moschops",
    // N
    "Nameless",
    // O
    "Oasisaur", "Onyc", "Otter", "Oviraptor", "Ovis",
    // P
    "Pachy", "Pachyrhinosaurus", "Palaeoctopus", "Paraceratherium",
    "Parasaur", "Pegomastax", "Pelagornis", "Phiomia", "Phoenix",
    "Piranha", "Plesiosaur", "Procoptodon", "Pteranodon",
    "Pulmonoscorpius", "Purlovia", "Pyromane",
    // Q
    "Quetzal",
    // R
    "Raptor", "Ravager", "Reaper", "Rex", "Rhyniognatha", "Rock Drake",
    "Rock Elemental", "Roll Rat",
    // S
    "Sabertooth", "Sabertooth Salmon", "Sarco", "Scout", "Seeker",
    "Shadowmane", "Shastasaurus", "Shinehorn", "Snow Owl", "Spino",
    "Stegosaurus",
    // T
    "Tapejara", "Terror Bird", "Therizinosaurus", "Thorny Dragon",
    "Thylacoleo", "Tidepup", "Titanoboa", "Titanomyrma", "Titanosaur",
    "Triceratops", "Trilobite", "Troodon", "Tropeognathus", "Tusoteuthis",
    // U
    "Unicorn",
    // V
    "Veilwyn", "Velonasaur", "Vulture",
    // W
    "Woolly Rhino",
    "Wyvern", "Fire Wyvern", "Lightning Wyvern", "Poison Wyvern",
    "Ice Wyvern", "Blood Crystal Wyvern", "Ember Crystal Wyvern",
    "Tropical Crystal Wyvern", "Forest Wyvern", "Sand Lightning Wyvern",
    "Zombie Wyvern",
    // X
    "Xiphactinus",
    // Y
    "Yeti", "Yi Ling", "Yutyrannus",
  ],

  IMAGENES: {
    "Achatina":                "https://ark.wiki.gg/images/6/60/Achatina.png",
    "Acrocanthosaurus":        "https://ark.wiki.gg/images/1/1e/Acrocanthosaurus.png",
    "Allosaurus":              "https://ark.wiki.gg/images/0/09/Allosaurus.png",
    "Ammonite":                "https://ark.wiki.gg/images/3/3c/Ammonite.png",
    "Angler":                  "https://ark.wiki.gg/images/7/7b/Anglerfish.png",
    "Ankylosaurus":            "https://ark.wiki.gg/images/3/3a/Ankylosaurus.png",
    "Araneo":                  "https://ark.wiki.gg/images/d/df/Araneo.png",
    "Archaeopteryx":           "https://ark.wiki.gg/images/9/96/Archaeopteryx.png",
    "Archelon":                "https://ark.wiki.gg/images/a/a2/Archelon.png",
    "Argentavis":              "https://ark.wiki.gg/images/6/65/Argentavis.png",
    "Armadoggo":               "https://ark.wiki.gg/images/5/5e/Armadoggo.png",
    "Arthropluera":            "https://ark.wiki.gg/images/c/cb/Arthropluera.png",
    "Astrocetus":              "https://ark.wiki.gg/images/9/9a/Astrocetus.png",
    "Astrodelphis":            "https://ark.wiki.gg/images/6/6e/Astrodelphis.png",
    "Baryonyx":                "https://ark.wiki.gg/images/4/4a/Baryonyx.png",
    "Basilisk":                "https://ark.wiki.gg/images/6/63/Basilisk.png",
    "Basilosaurus":            "https://ark.wiki.gg/images/3/3b/Basilosaurus.png",
    "Beelzebufo":              "https://ark.wiki.gg/images/2/27/Beelzebufo.png",
    "Bison":                   "https://ark.wiki.gg/images/c/c3/Bison.png",
    "Bloodstalker":            "https://ark.wiki.gg/images/5/52/Bloodstalker.png",
    "Brontosaurus":            "https://ark.wiki.gg/images/3/3b/Brontosaurus.png",
    "Bulbdog":                 "https://ark.wiki.gg/images/6/64/Bulbdog.png",
    "Burrowbuck":              "https://ark.wiki.gg/images/b/b2/Burrowbuck.png",
    "Carbonemys":              "https://ark.wiki.gg/images/4/40/Carbonemys.png",
    "Carcharodontosaurus":     "https://ark.wiki.gg/images/3/30/Carcharodontosaurus.png",
    "Carnotaurus":             "https://ark.wiki.gg/images/c/c5/Carnotaurus.png",
    "Castoroides":             "https://ark.wiki.gg/images/e/dc/Castoroides.png",
    "Cat":                     "https://ark.wiki.gg/images/3/3e/Cat.png",
    "Ceratosaurus":            "https://ark.wiki.gg/images/5/56/Ceratosaurus.png",
    "Chalicotherium":          "https://ark.wiki.gg/images/1/12/Chalicotherium.png",
    "Cnidaria":                "https://ark.wiki.gg/images/b/b4/Cnidaria.png",
    "Coelacanth":              "https://ark.wiki.gg/images/3/30/Coelacanth.png",
    "Compy":                   "https://ark.wiki.gg/images/1/1e/Compy.png",
    "Cosmo":                   "https://ark.wiki.gg/images/3/3e/Cosmo.png",
    "Cryolophosaurus":         "https://ark.wiki.gg/images/9/96/Cryolophosaurus.png",
    "Daeodon":                 "https://ark.wiki.gg/images/a/a3/Daeodon.png",
    "Deathworm":               "https://ark.wiki.gg/images/6/6e/Deathworm.png",
    "Deinonychus":             "https://ark.wiki.gg/images/c/c3/Deinonychus.png",
    "Deinosuchus":             "https://ark.wiki.gg/images/d/d0/Deinosuchus.png",
    "Deinotherium":            "https://ark.wiki.gg/images/7/7e/Deinotherium.png",
    "Desmodus":                "https://ark.wiki.gg/images/0/07/Desmodus.png",
    "Dilophosaur":             "https://ark.wiki.gg/images/9/96/Dilophosaurus.png",
    "Dimetrodon":              "https://ark.wiki.gg/images/4/4a/Dimetrodon.png",
    "Dimorphodon":             "https://ark.wiki.gg/images/4/45/Dimorphodon.png",
    "Diplocaulus":             "https://ark.wiki.gg/images/6/60/Diplocaulus.png",
    "Diplodocus":              "https://ark.wiki.gg/images/a/ad/Diplodocus.png",
    "Dire Bear":               "https://ark.wiki.gg/images/7/77/Dire_Bear.png",
    "Direwolf":                "https://ark.wiki.gg/images/a/a0/Direwolf.png",
    "Dodo":                    "https://ark.wiki.gg/images/8/80/Dodo.png",
    "Doedicurus":              "https://ark.wiki.gg/images/2/22/Doedicurus.png",
    "Drakeling":               "https://ark.wiki.gg/images/d/d3/Drakeling.png",
    "Dreadnoughtus":           "https://ark.wiki.gg/images/3/38/Dreadnoughtus.png",
    "Dung Beetle":             "https://ark.wiki.gg/images/8/8a/Dung_Beetle.png",
    "Dunkleosteus":            "https://ark.wiki.gg/images/1/1d/Dunkleosteus.png",
    "Electrophorus":           "https://ark.wiki.gg/images/e/e1/Electrophorus.png",
    "Enforcer":                "https://ark.wiki.gg/images/e/eb/Enforcer.png",
    "Enigmasaur":              "https://ark.wiki.gg/images/e/e5/Enigmasaur.png",
    "Equus":                   "https://ark.wiki.gg/images/0/0b/Equus.png",
    "Eurypterid":              "https://ark.wiki.gg/images/5/54/Eurypterid.png",
    "Fasolasuchus":            "https://ark.wiki.gg/images/a/ae/Fasolasuchus.png",
    "Featherlight":            "https://ark.wiki.gg/images/1/14/Featherlight.png",
    "Ferox":                   "https://ark.wiki.gg/images/4/4c/Ferox_Large.png",
    "Gacha":                   "https://ark.wiki.gg/images/d/d8/Gacha.png",
    "Gallimimus":              "https://ark.wiki.gg/images/e/e0/Gallimimus.png",
    "Gasbags":                 "https://ark.wiki.gg/images/6/6c/Gasbags.png",
    "Giant Bee":               "https://ark.wiki.gg/images/7/77/Giant_Bee.png",
    "Gigadesmodus":            "https://ark.wiki.gg/images/0/07/Desmodus.png",
    "Giganotosaurus":          "https://ark.wiki.gg/images/c/c3/Giganotosaurus.png",
    "Gigantopithecus":         "https://ark.wiki.gg/images/7/72/Gigantopithecus.png",
    "Gigantoraptor":           "https://ark.wiki.gg/images/5/52/Gigantoraptor.png",
    "Gloon":                   "https://ark.wiki.gg/images/5/5e/Gloon.png",
    "Glowbug":                 "https://ark.wiki.gg/images/3/3c/Glowbug.png",
    "Glowtail":                "https://ark.wiki.gg/images/c/cd/Glowtail.png",
    "Griffin":                 "https://ark.wiki.gg/images/3/30/Griffin.png",
    "Helicoprion":             "https://ark.wiki.gg/images/6/6b/Helicoprion.png",
    "Hesperornis":             "https://ark.wiki.gg/images/2/29/Hesperornis.png",
    "Hyaenodon":               "https://ark.wiki.gg/images/4/46/Hyaenodon.png",
    "Ichthyornis":             "https://ark.wiki.gg/images/6/6b/Ichthyornis.png",
    "Ichthyosaurus":           "https://ark.wiki.gg/images/6/6a/Ichthyosaurus.png",
    "Iguanodon":               "https://ark.wiki.gg/images/a/ac/Iguanodon.png",
    "Jerboa":                  "https://ark.wiki.gg/images/6/67/Jerboa.png",
    "Jug Bug":                 "https://ark.wiki.gg/images/7/71/Jug_Bug.png",
    "Kairuku":                 "https://ark.wiki.gg/images/a/a2/Kairuku.png",
    "Kaprosuchus":             "https://ark.wiki.gg/images/b/b7/Kaprosuchus.png",
    "Karkinos":                "https://ark.wiki.gg/images/5/5e/Karkinos.png",
    "Kentrosaurus":            "https://ark.wiki.gg/images/d/dd/Kentrosaurus.png",
    "Lamprey":                 "https://ark.wiki.gg/images/b/b4/Lamprey.png",
    "Leech":                   "https://ark.wiki.gg/images/5/55/Leech.png",
    "Leedsichthys":            "https://ark.wiki.gg/images/3/30/Leedsichthys.png",
    "Liopleurodon":            "https://ark.wiki.gg/images/0/0d/Liopleurodon.png",
    "Lymantria":               "https://ark.wiki.gg/images/e/ea/Lymantria.png",
    "Lystrosaurus":            "https://ark.wiki.gg/images/6/67/Lystrosaurus.png",
    "Maewing":                 "https://ark.wiki.gg/images/5/53/Maewing.png",
    "Maeguana":                "https://ark.wiki.gg/images/5/5e/Maeguana.png",
    "Magmasaur":               "https://ark.wiki.gg/images/a/a8/Magmasaur.png",
    "Mammoth":                 "https://ark.wiki.gg/images/3/34/Mammoth.png",
    "Managarmr":               "https://ark.wiki.gg/images/e/ec/Managarmr.png",
    "Manta":                   "https://ark.wiki.gg/images/8/86/Manta.png",
    "Mantis":                  "https://ark.wiki.gg/images/e/ef/Mantis.png",
    "Megalania":               "https://ark.wiki.gg/images/5/56/Megalania.png",
    "Megaloceros":             "https://ark.wiki.gg/images/0/05/Megaloceros.png",
    "Megalodon":               "https://ark.wiki.gg/images/1/1a/Megalodon.png",
    "Megalosaurus":            "https://ark.wiki.gg/images/a/a0/Megalosaurus.png",
    "Meganeura":               "https://ark.wiki.gg/images/6/6e/Meganeura.png",
    "Megatherium":             "https://ark.wiki.gg/images/1/1a/Megatherium.png",
    "Megaraptor":              "https://ark.wiki.gg/images/0/07/Raptor.png",
    "Mesopithecus":            "https://ark.wiki.gg/images/2/28/Mesopithecus.png",
    "Microraptor":             "https://ark.wiki.gg/images/5/57/Microraptor.png",
    "Morellatops":             "https://ark.wiki.gg/images/a/ae/Morellatops.png",
    "Mosasaurus":              "https://ark.wiki.gg/images/a/a8/Mosasaurus.png",
    "Moschops":                "https://ark.wiki.gg/images/0/05/Moschops.png",
    "Nameless":                "https://ark.wiki.gg/images/5/54/Nameless.png",
    "Oasisaur":                "https://ark.wiki.gg/images/0/0e/Oasisaur.png",
    "Onyc":                    "https://ark.wiki.gg/images/f/f6/Onyc.png",
    "Otter":                   "https://ark.wiki.gg/images/0/0a/Otter.png",
    "Oviraptor":               "https://ark.wiki.gg/images/a/a8/Oviraptor.png",
    "Ovis":                    "https://ark.wiki.gg/images/0/07/Ovis.png",
    "Pachy":                   "https://ark.wiki.gg/images/1/14/Pachy.png",
    "Pachyrhinosaurus":        "https://ark.wiki.gg/images/2/20/Pachyrhinosaurus.png",
    "Palaeoctopus":            "https://ark.wiki.gg/images/3/32/Palaeoctopus.png",
    "Paraceratherium":         "https://ark.wiki.gg/images/7/74/Paraceratherium.png",
    "Parasaur":                "https://ark.wiki.gg/images/7/76/Parasaur.png",
    "Pegomastax":              "https://ark.wiki.gg/images/c/c2/Pegomastax.png",
    "Pelagornis":              "https://ark.wiki.gg/images/f/fa/Pelagornis.png",
    "Phiomia":                 "https://ark.wiki.gg/images/0/04/Phiomia.png",
    "Phoenix":                 "https://ark.wiki.gg/images/1/12/Phoenix.png",
    "Piranha":                 "https://ark.wiki.gg/images/3/34/Piranha.png",
    "Plesiosaur":              "https://ark.wiki.gg/images/1/11/Plesiosaur.png",
    "Procoptodon":             "https://ark.wiki.gg/images/5/51/Procoptodon.png",
    "Pteranodon":              "https://ark.wiki.gg/images/c/c7/Pteranodon.png",
    "Pulmonoscorpius":         "https://ark.wiki.gg/images/9/91/Pulmonoscorpius.png",
    "Purlovia":                "https://ark.wiki.gg/images/4/42/Purlovia.png",
    "Pyromane":                "https://ark.wiki.gg/images/6/6e/Pyromane.png",
    "Quetzal":                 "https://ark.wiki.gg/images/4/4a/Quetzal.png",
    "Raptor":                  "https://ark.wiki.gg/images/0/07/Raptor.png",
    "Ravager":                 "https://ark.wiki.gg/images/d/df/Ravager.png",
    "Reaper":                  "https://ark.wiki.gg/images/4/4c/Reaper_King.png",
    "Rex":                     "https://ark.wiki.gg/images/0/04/Rex.png",
    "Rhyniognatha":            "https://ark.wiki.gg/images/5/52/Rhyniognatha.png",
    "Rock Drake":              "https://ark.wiki.gg/images/d/dd/Rock_Drake.png",
    "Rock Elemental":          "https://ark.wiki.gg/images/8/82/Rock_Elemental.png",
    "Roll Rat":                "https://ark.wiki.gg/images/b/ba/Roll_Rat.png",
    "Sabertooth":              "https://ark.wiki.gg/images/0/03/Sabertooth.png",
    "Sabertooth Salmon":       "https://ark.wiki.gg/images/3/38/Sabertooth_Salmon.png",
    "Sarco":                   "https://ark.wiki.gg/images/6/64/Sarco.png",
    "Scout":                   "https://ark.wiki.gg/images/5/57/Scout.png",
    "Seeker":                  "https://ark.wiki.gg/images/5/5b/Seeker.png",
    "Shadowmane":              "https://ark.wiki.gg/images/0/01/Shadowmane.png",
    "Shastasaurus":            "https://ark.wiki.gg/images/5/5e/Shastasaurus.png",
    "Shinehorn":               "https://ark.wiki.gg/images/2/20/Shinehorn.png",
    "Snow Owl":                "https://ark.wiki.gg/images/d/df/Snow_Owl.png",
    "Spino":                   "https://ark.wiki.gg/images/0/08/Spino.png",
    "Stegosaurus":             "https://ark.wiki.gg/images/c/cc/Stegosaurus.png",
    "Tapejara":                "https://ark.wiki.gg/images/4/41/Tapejara.png",
    "Terror Bird":             "https://ark.wiki.gg/images/a/a4/Terror_Bird.png",
    "Therizinosaurus":         "https://ark.wiki.gg/images/2/23/Therizinosaurus.png",
    "Thorny Dragon":           "https://ark.wiki.gg/images/1/1d/Thorny_Dragon.png",
    "Thylacoleo":              "https://ark.wiki.gg/images/4/4e/Thylacoleo.png",
    "Tidepup":                 "https://ark.wiki.gg/images/4/4e/Tidepup.png",
    "Titanoboa":               "https://ark.wiki.gg/images/c/cd/Titanoboa.png",
    "Titanomyrma":             "https://ark.wiki.gg/images/5/52/Titanomyrma.png",
    "Titanosaur":              "https://ark.wiki.gg/images/d/dc/Titanosaur.png",
    "Triceratops":             "https://ark.wiki.gg/images/6/62/Triceratops.png",
    "Trilobite":               "https://ark.wiki.gg/images/4/4b/Trilobite.png",
    "Troodon":                 "https://ark.wiki.gg/images/a/a7/Troodon.png",
    "Tropeognathus":           "https://ark.wiki.gg/images/3/34/Tropeognathus.png",
    "Tusoteuthis":             "https://ark.wiki.gg/images/b/b7/Tusoteuthis.png",
    "Unicorn":                 "https://ark.wiki.gg/images/0/0b/Equus.png",
    "Veilwyn":                 "https://ark.wiki.gg/images/5/5e/Veilwyn.png",
    "Velonasaur":              "https://ark.wiki.gg/images/3/35/Velonasaur.png",
    "Vulture":                 "https://ark.wiki.gg/images/a/a2/Vulture.png",
    "Woolly Rhino":            "https://ark.wiki.gg/images/2/23/Woolly_Rhino.png",
    "Wyvern":                  "https://ark.wiki.gg/images/4/46/Lightning_Wyvern.png",
    "Fire Wyvern":             "https://ark.wiki.gg/images/f/f6/Fire_Wyvern.png",
    "Lightning Wyvern":        "https://ark.wiki.gg/images/4/46/Lightning_Wyvern.png",
    "Poison Wyvern":           "https://ark.wiki.gg/images/b/b4/Poison_Wyvern.png",
    "Ice Wyvern":              "https://ark.wiki.gg/images/d/d0/Ice_Wyvern.png",
    "Blood Crystal Wyvern":    "https://ark.wiki.gg/images/1/1b/Blood_Crystal_Wyvern.png",
    "Ember Crystal Wyvern":    "https://ark.wiki.gg/images/5/5e/Ember_Crystal_Wyvern.png",
    "Tropical Crystal Wyvern": "https://ark.wiki.gg/images/8/87/Tropical_Crystal_Wyvern.png",
    "Forest Wyvern":           "https://ark.wiki.gg/images/f/f6/Fire_Wyvern.png",
    "Sand Lightning Wyvern":   "https://ark.wiki.gg/images/4/46/Lightning_Wyvern.png",
    "Zombie Wyvern":           "https://ark.wiki.gg/images/4/46/Lightning_Wyvern.png",
    "Xiphactinus":             "https://ark.wiki.gg/images/0/0e/Xiphactinus.png",
    "Yeti":                    "https://ark.wiki.gg/images/5/56/Yeti.png",
    "Yi Ling":                 "https://ark.wiki.gg/images/3/3e/Yi_Ling.png",
    "Yutyrannus":              "https://ark.wiki.gg/images/c/c9/Yutyrannus.png",
  }
};
